// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tkf_Complaint_System.Data;

#nullable disable

namespace Tkf_Complaint_System.Migrations
{
    [DbContext(typeof(Tkf_Complaint_System_Context))]
    [Migration("20231004113635_Client_Tables_Migration")]
    partial class Client_Tables_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tkf_Complaint_System.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.HasKey("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Karachi",
                            DistrictId = 1
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Quetta",
                            DistrictId = 2
                        });
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.ClientInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallBackMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("clientInformation");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer");

                    b.HasKey("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            DistrictName = "Karachi",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 2,
                            DistrictName = "Quetta",
                            ProvinceId = 1
                        });
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComplaintDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComplaintFeedbackRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedBackPriority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectId");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UCId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectId");

                    b.HasIndex("UCId");

                    b.ToTable("projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            ProjectName = "Karachi",
                            UCId = 2
                        },
                        new
                        {
                            ProjectId = 2,
                            ProjectName = "Quetta",
                            UCId = 1
                        });
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Project_tbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Donor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectDistrict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectProvince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectUC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("project_Tbls");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProvinceId");

                    b.ToTable("provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            ProvinceName = "Baluchistan"
                        },
                        new
                        {
                            ProvinceId = 2,
                            ProvinceName = "Sindh"
                        });
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.UC", b =>
                {
                    b.Property<int>("UCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UCId"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("UCName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UCId");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("uCs");

                    b.HasData(
                        new
                        {
                            UCId = 1,
                            CityId = 1,
                            UCName = "North Karachi"
                        },
                        new
                        {
                            UCId = 2,
                            CityId = 2,
                            UCName = "Quetta Mariabad"
                        });
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.City", b =>
                {
                    b.HasOne("Tkf_Complaint_System.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.District", b =>
                {
                    b.HasOne("Tkf_Complaint_System.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Feedback", b =>
                {
                    b.HasOne("Tkf_Complaint_System.Models.ClientInformation", "ClientInformation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tkf_Complaint_System.Models.Project_tbl", "Project")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientInformation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Project", b =>
                {
                    b.HasOne("Tkf_Complaint_System.Models.UC", "UC")
                        .WithMany("Projects")
                        .HasForeignKey("UCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UC");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.UC", b =>
                {
                    b.HasOne("Tkf_Complaint_System.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tkf_Complaint_System.Models.District", null)
                        .WithMany("UCs")
                        .HasForeignKey("DistrictId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.ClientInformation", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.District", b =>
                {
                    b.Navigation("UCs");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Project_tbl", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Tkf_Complaint_System.Models.UC", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
